### ISSUE TITLE
Cannot pass dictionary type to read_from_all for from_position

### ISSUE THREAD

**Issue by jmshnds** [stefanondisponibile/eventstore_grpc#1]
When passing a dictionary type to the function `read_from_all` the check `isinstance(from_position, dict)` never happens because `from_position.upper()` will raise an exception.
```
AttributeError: 'dict' object has no attribute 'upper'
```

https://github.com/stefanondisponibile/eventstore_grpc/blob/7995d6a56409cd77490f26a1ff7b1ea8aff7abdc/eventstore_grpc/streams/read.py#L104

**Comment by stefanondisponibile** [comment]
Hey @jmshnds , thank you for raising this issue! Being still at an early stage, I wasn't expecting that (I'm actually still writing tests, so I can't guarantee everything's working as expected).

However, if you had a look at the code, or even tried it, I'd be curious on your opinions, or possible issues.
And of course you're welcome if you're willing to contribute 🙂

---

As you've seen, I've committed a very quick change that *should* fix the issue, but I'll probably come later into that for a better handling.
