### ISSUE TITLE
ModuleNotFoundError: No module named 'eventstore_grpc'

### ISSUE THREAD

**Issue by silviuvoicu** [stefanondisponibile/eventstore_grpc#3]
Hi, I wanted to test on my local machine, I clone it, change  to develop branch, run docker-compose but when to executes the script example I got this error: 
" from eventstore_grpc.client.event_store import EventStore
ModuleNotFoundError: No module named 'eventstore_grpc' "
I have create $PYTHONPATH in .bashrc file and give the address of the local folder where this project was downloaded. 
I also installed the grpc for Python 3.10.6.
What do I miss for this project to run? 
Do I have to run first compile-protos.sh?
Thank you.

**Comment by stefanondisponibile** [comment]
hello @silviuvoicu and thanks for reaching out!
That error is probably telling you that you don't have the library (i.e. `evenstore_grpc`). If you included your local folder in your `PYTHONPATH` please note that this package lives under a `src` directory, so you may probably want to add `./src` to your `PYTHONPATH` instead. You may also try to `pip install -e .` from the repository's main root.

However, I suggest you to [use poetry](https://python-poetry.org/docs/#installation) if you want to play around with the library.
After that, ensure you're using Python `>=3.10` and:

```bash
# install dependencies and the library in a virtual environment managed by Poetry
poetry install
docker compose down \
  && docker compose up -d \
  && echo 'Wait for EventStoreDB to be ready...' \
  && sleep 10 \
  && poetry run python scripts/example.py \
  && docker compose down
```

I will soon update the `README` with more clear instructions and bump the `python` version in the `pyproject.toml` file. :+1: 
Let me know if you were able to solve the problem!

**Comment by silviuvoicu** [comment]
Thank you, after adding src to the path, problem solved and it works as expected. I think that your example of eventstore grpc client for python could be used as guide for  a similar project but for php.
